### PR TITLE
FIX: Spectrum demo occasionally crashes with IOError

### PR DESCRIPTION
**Pull request by andrewcollette**
While running on OS X, the `spectrum.py` demo will occasionally crash inside PyAudio with `IOError: [Errno Input overflowed] -9981`.  This patch simply restarts the audio stream if that happens.

### CODE REVIEW

**Comment by corranwebster** [comment]
Probably want a comment in the `except` with a brief explanation of what you're doing.

Also, if it's always error number -9981 that you're seeing, you might want to check for that explicitly and raise otherwise to avoid masking other problems.

**Comment by andrewcollette** [comment]
OK, I have added a comment and check to prevent it from responding to a generic IOError.

**Comment by corranwebster** [comment]
LGTM

**Comment by andrewcollette** [comment]
Awesome.  Shall I merge directly into master or are there other steps to take?

**Comment by corranwebster** [comment]
Yes, it can be directly merged, but check with @jvkersch about _when_ he wants it merged: he is preparing to cut a release.  It would be good to get this in, but not essential.

If it is merged, then an appropriate entry should to be added to the changelog PR https://github.com/enthought/chaco/pull/321 before merging it.

**Comment by jvkersch** [comment]
Let's merge it now (I had my eye on it on Friday but wanted to hold off until Corran was back). I'll add the entry to #321.

**Pull request merged**
