### PR TITLE
Release 4.6.0

### PR DESCRIPTION
**Pull request by corranwebster**
Release branch for 4.6.0

### CODE REVIEW

**Comment by corranwebster** [comment]
With some issues with Enable, this installs and runs on OS X Python 2.7 and Python 3.5.

There seems to be some issues with the Contour plot c module on 3.5 while trying to run some examples:
```
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/abstract_window.py", line 468, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/component.py", line 424, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/component.py", line 766, in _draw
    self._dispatch_draw(layer, bb, view_bounds, mode)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/enable-4.6.0-py3.5-macosx-10.6-x86_64.egg/enable/component.py", line 796, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/chaco/base_2d_plot.py", line 204, in _draw_image
    self._render(gc)
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/chaco/contour_line_plot.py", line 85, in _render
    self._update_contours()
  File "/Users/cwebster/.edm/envs/test-chaco-3.5/lib/python3.5/site-packages/chaco/contour_line_plot.py", line 130, in _update_contours
    c = Cntr(xg, yg, data, ~mask)
SystemError: <class 'cntr.Cntr'> returned a result with an error set
```

**Comment by senganal** [comment]
@corranwebster  Is the above a blocking issue for `4.6.0` release ?

**Comment by corranwebster** [comment]
Yes, given that Python 3 compatibility is a major reason for the release.  As it currently stands, the contour plots aren't working properly on 3.5 and I haven't had time to investigate (something in the C-level code, I suspect).

**Comment by corranwebster** [comment]
The immediate issues seem to be fixed by the last-minute inclusions.  Hopefully release sometime in the next week.

**Pull request merged**
