### PR TITLE
DOC: Changelog entries.

### PR DESCRIPTION
**Pull request by jvkersch**
This adds entries in the changelog for the PRs that were merged since 4.5.0.

### CODE REVIEW

**Comment by jvkersch** [comment]
@corranwebster Quick review?

**Comment by corranwebster** [comment]
LGTM

**Comment by corranwebster** [comment]
@jvkersch do you want to include #326 in the upcoming release?

**Comment by jvkersch** [comment]
@corranwebster Yes, that would be good. I'll give it a look in the next few days, if nobody has already.

**Pull request merged**
