### PR TITLE
Fix selection alpha for line scatterplot

### PR DESCRIPTION
**Pull request by corranwebster**
Copy-paste error from scatterplot code, plus missing trait.

### CODE REVIEW

**Comment by jonathanrocher** [comment]
LGTM. Does this mean that we are missing a unit test to exercise the `_render` method?

**Comment by jwiggins** [comment]
This same missing trait is referenced in `ScatterPlot1D` too.

**Comment by corranwebster** [comment]
@jonathanrocher We were exercising `_render`, but not the branch that drew selections.  Tests are now added to do that (although they are really just smoke-tests).

@jwiggins Thanks. Fixed.

**Comment by corranwebster** [comment]
I am going to merge this today unless there are objections, as the fix is needed in a consulting project.

**Comment by jwiggins** [comment]
LGTM

**Comment by jonathanrocher** [comment]
@corranwebster This was missing an entry into the changelog. Mind adding that in a different PR?

**Pull request merged**
