### PR TITLE
Use travis ci containers

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
PR fails mainly because of issues with the new Pillow 3.0.0 (see https://github.com/enthought/enable/pull/215)

**Comment by corranwebster** [comment]
@itziakos is this good to merge now that tests are passing.

**Comment by itziakos** [comment]
It has been a while since the tests run. I will force another build and if all pass we should be good to go

**Comment by itziakos** [comment]
good to go :+1:

**Pull request merged**
