### PR TITLE
Feature: allow user control over axis title angle

### PR DESCRIPTION
**Pull request by jonathanrocher**
With the current code, the axis' title label has an angle fully determined by the orientation of the Axis. left-> 90, right -> 270, top/bottom -> 0.

This PR: 
* makes the existing `title_angle` attribute a Float Trait, and moves its derivation based on orientation to a `_title_angle_default` method, so that users can control it.
* tweaks a simple example to illustrate the new capability
* updates the docs to list the new trait.

### CODE REVIEW

**Comment by jonathanrocher** [comment]
CI failures unrelated.

**Comment by jvkersch** [comment]
@jonathanrocher I will look at this and your other PR asap.

**Comment by jvkersch** [comment]
LGTM, code looks good and I played around with the example.

(I merged master in this to make sure tests pass).

**Comment by jonathanrocher** [comment]
Thanks for the review @jvkersch !

**Pull request merged**
