### PR TITLE
REL: 4.8.0

### PR DESCRIPTION
**Pull request by jvkersch**
Picks up from #460 and adds three more sets of changes (#469, #470, #471)

@mdickinson Since you already reviewed the earlier release PR, do you want to have another look here?

### CODE REVIEW

**Comment by corranwebster** [comment]
LGTM

**Comment by mdickinson** [comment]
I hope this wasn't still waiting on me :-(.  I'll do some testing this afternoon, but the release needn't wait on that.

**Comment by jvkersch** [comment]
@mdickinson I'm embarrassed to say that when I created the release PR I managed to not include your fixes. I need to revisit that and create a `4.8.0-third-times-the-charm` release branch...

**Comment by mdickinson** [comment]
@jvkersch Okay, will wait on that. Please ping me on the new PR when it happens.

**Comment by jvkersch** [comment]
Replaced by #476

**Pull request closed without merging**
