### PR TITLE
Set cython "language_level" explicitly to 3

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR sets the Cython `language_level` explicitly to 3.

### CODE REVIEW

**Review by aaronayres35 — APPROVED** [review]
LGTM (I apologize for not opening issues for this!)
I no longer see the warnings:
```
[1/2] Cythonizing chaco/_cython_speedups.pyx
/Users/aayres/.edm/envs/test-chaco/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/aayres/Desktop/chaco/chaco/_cython_speedups.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
[2/2] Cythonizing chaco/downsample/_lttb.pyx
/Users/aayres/.edm/envs/test-chaco/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/aayres/Desktop/chaco/chaco/downsample/_lttb.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```
when building the sdist.

I believe this could have been done here as well (?):
https://github.com/enthought/chaco/blob/d3b7c374eaeb2b6a4ba194eed5751763f3d9b8d2/setup.py#L315
based off of https://stackoverflow.com/questions/34603628/how-to-specify-python-3-source-in-cythons-setup-py

But this works as expected. (not a suggested change)

**Comment by rahulporuri** [comment]
Thanks for the headsup @aaronayres35 - it's better to set `language_level` in a single place instead of setting it repeatedly in every single cython file, which can potentially lead to a bug if the developer forgets to add `language_level` to a new cython file.

**Comment by rahulporuri** [comment]
@aaronayres35 do you want to take another look at this PR before I merge?

**Review by aaronayres35 — APPROVED** [review]
LGTM

I tested building the sdist again after the change and there are no warnings

**Pull request merged**
