### PR TITLE
Update Documentation for 5.0.0

### PR DESCRIPTION
**Pull request by aaronayres35**
This PR updates the documentation for the 5.0.0 release.  Unfortunately, I realized a couple additional broken links in the built docs.  I did the unorthodox thing of fixing them before building the docs for this PR.  After this, I will open a PR to fix them in the docs source in the code base.  I figured the release is already tagged, but we want the served docs to not have the broken links.  I imagine the scenario of someone building the docs themselves not from master or the maint branch will be a rare occurrence.  

The steps I took were:
```
git clean -ffxd
git checkout 5.0.0
python ci/edmtool.py install
edm shell -e chaco-test-3.6-null
edm install scipy pyqt5
python setup.py install
exit
# fix a couple more broken links locally.  See PR #793 
python ci/edmtool.py docs
# move docs/build/html folder to my desktop
git stash # stash my fixes, this was used later for PR #793
git checkout gh-pages
git clean -ffxd
git pull
git checkout -b gh-pages-5.0
mkdir 4.8
mkdir 5.0
mv `ls -d [![:digit:]]*` 4.8/. # move old 4.8 built 
git add -u
git add 4.8/
git commit -m "move 4.8 build docs into a 4.8 folder"
# move html folder containing built docs into cwd
rsync -r --exclude="\.buildinfo" html/* 5.0/  # put 5.0 built docs in 5.0 folder
rm -r html
cp -r 5.0/* .
git add .
git commit -m "add 5.0 built docs to 5.0 folder and root directory"
```

To test:
`python -m http.server`

### CODE REVIEW

**Comment by aaronayres35** [comment]
It looks like appveyor / travis are required on the chaco gh-pages branch?  We won't be able to merge this PR until that is turned off

**Review by rahulporuri — APPROVED** [review]
Mostly LGTM - the link in the tools `ImageInspectorTool` still seems broken on this PR though.

**Comment by rahulporuri** [comment]
> It looks like appveyor / travis are required on the chaco gh-pages branch? We won't be able to merge this PR until that is turned off

I updated the settings - `gh-pages` now requires no status checks

**Comment by aaronayres35** [comment]
> Mostly LGTM - the link in the tools `ImageInspectorTool` still seems broken on this PR though.

🤦 nice catch, thank you! I will fix this before merging this PR.  Also, looking closer I have no idea why that is a `:download:` rather than just a link to the code on github like we do elsewhere in the docs... I will fix the link here, it can be updated more later (that whole Tools page is _very much still a WIP_)

**Pull request merged**
