### PR TITLE
Refactor image plot

### PR DESCRIPTION
**Pull request by tonysyu**
While adding some plotting capabilities to an `ImagePlot` subclass (see https://github.com/enthought/geolibs/pull/43), I ended up having to refactor `ImagePlot` quite a bit.

This PR cleans up some of the coordinate transforms in `ImagePlot` and fixes an issue with negative screen sizes (see https://github.com/enthought/enable/issues/109). I've also added tests, but I'm not sure how robust this testing is: It requires precise pixel positions in the rendered image. (This positioning is achieved using a tweaked index grid, tweaked plot bounds, and slicing some "extra" rows/columns off the rendered image. Probably a bit fragile :P)

### CODE REVIEW

**Comment by tonysyu** [comment]
Bump @cfarrow (or @corranwebster, if you're looking for something to review ;)

**Comment by corranwebster** [comment]
@tonysyu Could you add a brief summary of the PR to the `CHANGES.txt`.

**Comment by corranwebster** [comment]
Having been in the Chaco codebase for a bit the last week or two, I think some of the issues Chris was seeing may be due to this: https://github.com/enthought/chaco/blame/master/chaco/plot_graphics_context.py#L14

It seems that sometimes Chaco wants to play games with shifting half pixels compared to Kiva.  That comment claims Kiva is wrong, but I don't know if that is in fact the case (and I don't know who the author of the comment is): my expectation is that the coordinate system should have integer values for the edges of the pixels (this is pretty standard, see the HTML Canvas element, for example) and half-integer values for the center of pixels.

In any case, this PR seems fine apart from the minor comment about updating the changelog.

**Comment by tonysyu** [comment]
@corranwebster: Thanks for reviewing! Changelog comment added.

**Comment by tonysyu** [comment]
:tada:

**Comment by jwiggins** [comment]
:golf: :clap:

**Pull request merged**
