### PR TITLE
Remove commented out code

### PR DESCRIPTION
**Pull request by aaronayres35**
This PR simply removes a few sections of commented out code

### CODE REVIEW

**Review by rahulporuri — APPROVED** [review]
LGTM. Not sure what `_pickles` is.

**Comment by rahulporuri** [comment]
Note that there are a couple of other instances of `_pickle*` that are commented which can also be removed. And if i understand correctly, we can also remove the persistence related methods - `__getstate__` and `__setstate__`.

I tried digging and at the bottom of the search - i still find these lines commented. I don't know which PR/why these lines were commented out.

**Comment by corranwebster** [comment]
> LGTM. Not sure what `_pickles` is.

It looks like it's used by the `Serializable` class: https://github.com/enthought/chaco/blob/e3423614d654a203bd82ee087c085abe13b465b1/chaco/serializable.py which even has tests https://github.com/enthought/chaco/blob/e3423614d654a203bd82ee087c085abe13b465b1/chaco/tests/serializable_base.py but isn't used anywhere in Chaco.

Modern usage would be to mark traits as `transient` if you _don't_ want them serialized (which is automatic for property and delegate traits).

The whole system can probably go.

**Comment by corranwebster** [comment]
I've added #583 for dealing with `__getstate__` and `__setstate__`.

The `_post_load` methods are more interesting, because they hint at things which might go into a `traits_init` function and allow simplification of `__init__` functions, but that's a bigger and more complex job.

**Pull request merged**
