### PR TITLE
Added MinorPlotAxis

### PR DESCRIPTION
**Pull request by stevenengler**
Added `MinorPlotAxis`, which is a `PlotAxis` with smaller ticks, smaller interval, and no tick labels. This should not break anything, the only change was to `auto_interval()`, which I added an optional argument to.

This originated from the stackoverflow question here:
https://stackoverflow.com/questions/34755769/minor-ticks-in-chaco-plot/34833938#34833938

image

``` python
if __name__ == "__main__":
    from traits.etsconfig.api import ETSConfig
    ETSConfig.toolkit = 'qt4'
    #
    import warnings
    warnings.filterwarnings(action = "ignore", category = FutureWarning, module="chaco")
    warnings.filterwarnings(action = "ignore", category = FutureWarning, module="traits")
#
from PySide import QtGui, QtCore
import numpy as np
from enable.api import Component, Container, Window
from chaco.api import *
import sys
#
class ChacoPlot(QtGui.QWidget):
    def __init__(self, parent=None):
        super(ChacoPlot, self).__init__(parent)
        #
        self.container = OverlayPlotContainer(padding=40)
        #
        self.enableWindow = Window(self, -1, component=self.container)
        windowLayout = QtGui.QVBoxLayout(self)
        windowLayout.addWidget(self.enableWindow.control)
        #
        self.xRange = DataRange1D()
        self.yRange = DataRange1D()
        #
        self.xMapper = LinearMapper(range=self.xRange)
        self.yMapper = LinearMapper(range=self.yRange)
        #
        self.plots = {}
        # keep a list of plots added to the container
    #
    def setMinimumSize(self, width, height):
        self.enableWindow.control.setMinimumSize(width, height)
    #
    def addLine(self, name, plotType):
        xSource = ArrayDataSource([0])
        ySource = ArrayDataSource([0])
        #
        self.xRange.add(xSource)
        self.yRange.add(ySource)
        #
        index_mapper = self.xMapper
        value_mapper = self.yMapper
        #
        # plotType is a class name
        plot = plotType(    index = xSource,
                            value = ySource,
                            index_mapper = index_mapper,
                            value_mapper = value_mapper,
                            visible = False
                       )
        #
        self.container.add(plot)
        #
        self.plots[name] = {'plot':plot, 'xSource':xSource, 'ySource':ySource}
    #
    def updateLine(self, name, xData, yData):
        plot = self.plots[name]
        #
        if np.array(xData).size != 0:
            plot['plot'].visible = True
        else:
            plot['plot'].visible = False
            xData = [0]
            yData = [0]
        #
        plot['xSource'].set_data(xData)
        plot['ySource'].set_data(yData)
    #
    def addAxis(self, plotName, orientation):
        plot = self.plots[plotName]['plot']
        #
        if orientation == 'top' or orientation == 'bottom':
            mapper = self.xMapper
        if orientation == 'left' or orientation == 'right':
            mapper = self.yMapper
        #
        axis = PlotAxis(plot, orientation=orientation, mapper=mapper)
        plot.overlays.append(axis)
        #
        return axis
    #
    def addMinorAxis(self, plotName, orientation):
        plot = self.plots[plotName]['plot']
        #
        if orientation == 'top' or orientation == 'bottom':
            mapper = self.xMapper
            range = self.xRange
        if orientation == 'left' or orientation == 'right':
            mapper = self.yMapper
            range = self.yRange
        #
        newAxis = MinorPlotAxis(plot, orientation=orientation, mapper=mapper)
        plot.overlays.append(newAxis)
        #
        return axis
    #
#
if __name__ == "__main__":
    appQT = QtGui.QApplication.instance()
    #
    x1 = np.arange(300)/18.0
    y1 = np.sin(x1)
    x2 = np.arange(300)/18.0
    y2 = 2.0*np.cos(x2)
    #
    plot = ChacoPlot()
    plot.setMinimumSize(400,300)
    #
    plot.addLine('line1', LinePlot)
    plot.addLine('line2', LinePlot)
    plot.updateLine('line1', x1, y1)
    plot.updateLine('line2', x2, y2)
    #
    plot.addAxis('line1', 'bottom')
    plot.addAxis('line1', 'left')
    plot.addMinorAxis('line1', 'bottom')
    plot.addMinorAxis('line1', 'left')
    #
    plot.show()
    appQT.exec_()
```

### CODE REVIEW

**Comment by corranwebster** [comment]
Thanks for the contribution!  I think that this is a reasonably good solution for a common use case (the only better way would be a subclass of `Axis` which has two tick generators and two sets of tick styles, and that's pretty awkward...)

The only potential improvement I would suggest is that `axis_line_visible` should probably default to `False` for this new class, just to prevent overdrawing the axis line unnecessarily.

**Comment by jonathanrocher** [comment]
Yes, thanks @stevenengler . For this PR to be merged, please add:
1. some unit tests for the new functionality
2. an entry in the changelog

Thanks!

**Comment by timdiller** [comment]
@stevenengler Thanks for doing this (I'm `TimD` on StackOverflow).  I'd love to see an addition to the docs for this.  I know the docs are sparse for Chaco, and I don't want to punish a good contribution by adding too much overhead, so let me know if you want help with that.

**Comment by stevenengler** [comment]
I thought about subclassing `PlotAxis` and adding another set of ticks (or simply adding an optional argument to `PlotAxis` to enable it), and I agree, it would make the API cleaner. The problem was any way I could think of doing it would have caused a lot of duplicate code or refactoring. I'm welcome to changes if you have any ideas.

For the unit tests and documentation, I'm not familiar with how it's done in Python. I don't mind adding these, but I've just got a couple questions. For the unit tests, I can follow the format of others in `chaco/tests`, but what kind of tests would I run on this PR (the axis)? And for the documentation, do I simply edit the `.rst` files directly, and that's all? Last question, how about an example in `chaco_tutorial.rst` and one or two lines to mention it in `overlays.rst`, does that sound good? I have previously spent hours wading through the documentation line-by-line, so if I have more time in the future, I'll try to contribute other things to it as well.

**Comment by timdiller** [comment]
@stevenengler you have the right idea for docs and unittests.  For testing, you would want to focus on `MinorTickGenerator` and `auto_interval`.  I'll try to write a few basic tests for `chaco/ticks.py` to show by example.  Unfortunately, that part of the code appears not to have any test coverage, so this might be a good time to add some.

**Comment by timdiller** [comment]
@corranwebster and @jonathanrocher will you weigh in on the tests?

**Comment by stevenengler** [comment]
Thanks for the unit tests @timdiller. I added a couple more simple tests for the `MinorTickGenerator`, feel free to make any changes or let me know. I will add to the documentation within the next few days.

**Comment by jvkersch** [comment]
@timdiller @corranwebster Should we merge this PR?

**Comment by stevenengler** [comment]
I added a short description and example in the `overlays.rst` file.

**Comment by jvkersch** [comment]
@stevenengler Thanks for adding the documentation. I'll merge this by the end of the day, unless there are any objections.

**Comment by timdiller** [comment]
@jvkersch what do you think about including the code in the OP as an example in the demos directory?

**Comment by jvkersch** [comment]
@timdiller I think that would be a good idea. I also wrote a small TraitsUI example to explore this functionality, perhaps we can add that instead (in order to be backend-agnostic).

**Comment by timdiller** [comment]
TraitsUI is probably the preferred way of demonstrating the usage.  Could you add your example?

**Comment by jvkersch** [comment]
I've added the example as a PR into this PR: https://github.com/stevenengler/chaco/pull/2

**Comment by stevenengler** [comment]
Thanks @jvkersch, I don't have the Chaco repo set up to test it, but the code looks good to me.

**Comment by jonathanrocher** [comment]
I test @jvkersch 's test and it works as expected.

**Comment by jvkersch** [comment]
@stevenengler Thanks for this contribution!

**Comment by stevenengler** [comment]
No problem! Just out of curiosity, are there any plans to put up a new 4.x release anytime soon? It would be nice to have the Python 3 support in the pip/canopy/chaco package lists.

**Comment by jvkersch** [comment]
Yep, one should be coming, probably before the end of the year.

**Pull request merged**
